### ISSUE TITLE
hard-wired absolute path?

### ISSUE THREAD

**Issue by martinhanes** [alqamabinsadiq/react-awesome-clock#1]
Hi, got this message with hello world example:

./node_modules/react-awesome-clock/lib/components/ReactClock.js
Module not found: Can't resolve 'C:\Users\Alqama\Desktop\react-clock\react-awesome-clock\node_modules\redbox-react\lib\index.js' in '_(removed my path)_/node_modules/react-awesome-clock/lib/components'

Martin

**Comment by farazsarwar113** [comment]
@alqamabinsadiq , Its easy ! 
I'll tell you a solution to fix your problem, 
Just modify the path files to relative and it will start working. 
i guess you followed these steps to create this lib 
https://medium.com/@lokhmakov/best-way-to-create-npm-packages-with-create-react-app-b24dd449c354
Do this and let me know if it works or not Thanks :)
